import { readdirSync, existsSync, writeFileSync, mkdirSync, rmSync, readFileSync, cpSync } from 'node:fs';
import { join } from 'node:path';
import { homedir } from 'node:os';
import { BaseAdapter } from './base.js';

export class CopilotAdapter extends BaseAdapter {
  get toolName() { return 'copilot'; }

  getUserDir() { return join(homedir(), '.copilot'); }

  getSkillsDir() { return join(this.getUserDir(), 'skills'); }

  getCommandsDir() { return join(this.getUserDir(), 'instructions'); }

  get capabilities() {
    return { hooks: false, skills: true, commands: true, plugin: false, mcpConfig: false, globalInstructions: true };
  }

  install(loomRoot, version) {
    const log = [];
    log.push(`Installing loom@${version} → ${this.toolName} (user-level)`);
    this._copySkills(loomRoot, log);
    this._copyTemplates(loomRoot, log);
    this._copyCommands(loomRoot, log);
    this._postInstall(loomRoot, version, log);
    return log;
  }

  uninstall(loomRoot) {
    const log = [];
    log.push(`Uninstalling loom → ${this.toolName} (user-level)`);
    this._removeSkills(log);
    this._removeTemplates(log);
    this._removeCommands(log);
    this._removeGlobalInstructions(log);
    return log;
  }

  _copyTemplates(loomRoot, log) {
    const src = join(loomRoot, 'templates');
    if (!existsSync(src)) return;

    const initProjectDir = join(this.getSkillsDir(), 'loom-init-project');
    if (!existsSync(initProjectDir)) {
      log.push('  templates: loom-init-project skill not found, skipped');
      return;
    }

    const dest = join(initProjectDir, 'templates');
    mkdirSync(dest, { recursive: true });
    cpSync(src, dest, { recursive: true, force: true });
    log.push('  templates: copied to loom-init-project skill dir');
  }

  _removeTemplates(log) {
    const initProjectDir = join(this.getSkillsDir(), 'loom-init-project', 'templates');
    if (existsSync(initProjectDir)) {
      rmSync(initProjectDir, { recursive: true, force: true });
      log.push('  templates: removed from loom-init-project skill dir');
    }
  }

  _removeGlobalInstructions(log) {
    const instructionsPath = join(this.getUserDir(), 'copilot-instructions.md');
    if (!existsSync(instructionsPath)) return;
    try {
      const content = readFileSync(instructionsPath, 'utf-8');
      if (!content.includes('Generated by loom')) {
        log.push('  copilot-instructions.md — not generated by loom, skipped');
        return;
      }
      rmSync(instructionsPath, { force: true });
      log.push('  copilot-instructions.md removed');
    } catch (e) {
      log.push(`  copilot-instructions.md: ${e.message}`);
    }
  }

  _postInstall(loomRoot, version, log) {
    this._ensureGlobalInstructions(loomRoot, version, log);
  }

  _ensureGlobalInstructions(loomRoot, version, log) {
    const instructionsPath = join(this.getUserDir(), 'copilot-instructions.md');
    if (existsSync(instructionsPath)) {
      log.push('  copilot-instructions.md already exists, skipping');
      return;
    }

    const skills = this._listSkills(loomRoot).map(s => `- ${s}`).join('\n');
    const content = `<!-- Generated by loom -->
# Loom — AI 工程化框架 (v${version})

Loom 是 AI 工程化框架

## Skills

以下 skills 已安装到 ~/.copilot/skills/:
${skills}

## 用法

在 Copilot CLI 中, 通过 /skills 命令查看可用 skills。
`;
    try {
      writeFileSync(instructionsPath, content, 'utf-8');
      log.push('  copilot-instructions.md written');
    } catch (e) {
      log.push(`  copilot-instructions.md: ${e.message}`);
    }
  }

  _listSkills(loomRoot) {
    const skillsDir = join(loomRoot, 'skills');
    if (!existsSync(skillsDir)) return [];
    return readdirSync(skillsDir, { withFileTypes: true })
      .filter(e => e.isDirectory())
      .map(e => e.name);
  }
}
