import { readdirSync, existsSync, writeFileSync, rmSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { homedir } from 'node:os';
import { BaseAdapter } from './base.js';

export class CopilotAdapter extends BaseAdapter {
  get toolName() { return 'copilot'; }

  getUserDir() { return join(homedir(), '.copilot'); }

  getSkillsDir() { return join(this.getUserDir(), 'skills'); }

  getCommandsDir() { return join(this.getUserDir(), 'instructions'); }

  uninstall(loomRoot) {
    const log = [];
    log.push(`Uninstalling loom → ${this.toolName} (user-level)`);
    this._removeSkills(log);
    this._removeCommands(log);
    this._removeGlobalInstructions(log);
    return log;
  }

  _removeGlobalInstructions(log) {
    const instructionsPath = join(this.getUserDir(), 'copilot-instructions.md');
    if (!existsSync(instructionsPath)) return;
    try {
      const content = readFileSync(instructionsPath, 'utf-8');
      if (!content.includes('Generated by loom')) {
        log.push('  copilot-instructions.md — not generated by loom, skipped');
        return;
      }
      rmSync(instructionsPath, { force: true });
      log.push('  copilot-instructions.md removed');
    } catch (e) {
      log.push(`  copilot-instructions.md: ${e.message}`);
    }
  }

  _postInstall(loomRoot, version, log) {
    this._ensureGlobalInstructions(loomRoot, version, log);
  }

  _ensureGlobalInstructions(loomRoot, version, log) {
    const instructionsPath = join(this.getUserDir(), 'copilot-instructions.md');
    if (existsSync(instructionsPath)) {
      log.push('  copilot-instructions.md already exists, skipping');
      return;
    }

    const skills = this._listSkills(loomRoot).map(s => `- ${s}`).join('\n');
    const content = `<!-- Generated by loom -->
# Loom — AI 工程化框架 (v${version})

Loom 是 AI 工程化框架, 提供 5 步流水线、项目宪章、5 维审查、进度追踪。

## Skills

以下 skills 已安装到 ~/.copilot/skills/:
${skills}

## 用法

在 Copilot CLI 中, 通过 /skills 命令查看可用 skills。
`;
    try {
      writeFileSync(instructionsPath, content, 'utf-8');
      log.push('  copilot-instructions.md written');
    } catch (e) {
      log.push(`  copilot-instructions.md: ${e.message}`);
    }
  }

  _listSkills(loomRoot) {
    const skillsDir = join(loomRoot, 'skills');
    if (!existsSync(skillsDir)) return [];
    return readdirSync(skillsDir, { withFileTypes: true })
      .filter(e => e.isDirectory())
      .map(e => e.name);
  }
}
