#!/usr/bin/env node
/**
 * generate-tooling.mjs — Generate src/generated/tooling.js from config/tools.schema.json
 *
 * Usage: node scripts/generate-tooling.mjs
 *
 * The generated file is the runtime single-source-of-truth.
 * Edit config/tools.schema.json, then re-run this script.
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const SCHEMA_PATH = join(ROOT, 'config', 'tools.schema.json');
const OUT_DIR = join(ROOT, 'src', 'generated');
const OUT_PATH = join(OUT_DIR, 'tooling.js');

// ── Load & validate schema ─────────────────────────────────────────────
const schema = JSON.parse(readFileSync(SCHEMA_PATH, 'utf-8'));

if (!schema.version || !Array.isArray(schema.tools)) {
  console.error('error: config/tools.schema.json must have "version" (int) and "tools" (array)');
  process.exit(1);
}

const ids = schema.tools.map(t => t.id);
const dupes = ids.filter((id, i) => ids.indexOf(id) !== i);
if (dupes.length > 0) {
  console.error(`error: duplicate tool ids: ${dupes.join(', ')}`);
  process.exit(1);
}

// ── Build output ───────────────────────────────────────────────────────
const header = `/**
 * AUTO-GENERATED by scripts/generate-tooling.mjs — DO NOT EDIT
 * Source: config/tools.schema.json (version ${schema.version})
 * Regenerate: node scripts/generate-tooling.mjs
 */`;

const toolEntries = schema.tools.map(t => {
  const pluginMeta = t.pluginMeta === null ? 'null' : JSON.stringify(t.pluginMeta);
  return `  {
    id: ${JSON.stringify(t.id)},
    displayName: ${JSON.stringify(t.displayName)},
    supportLevel: ${JSON.stringify(t.supportLevel)},
    platforms: ${JSON.stringify(t.platforms)},
    hooksSupport: ${t.hooksSupport},
    pluginMeta: ${pluginMeta},
    entryFilename: ${JSON.stringify(t.entryFilename)},
    description: ${JSON.stringify(t.description)},
  }`;
});

const code = `${header}

export const SCHEMA_VERSION = ${schema.version};

export const TOOLS = [
${toolEntries.join(',\n')}
];

/** @type {string[]} All tool ids (including planned) */
export const TOOL_IDS = TOOLS.map(t => t.id);

/** @type {string[]} Only tools with implemented adapters */
export const IMPLEMENTED_TOOL_IDS = TOOLS
  .filter(t => t.supportLevel !== 'planned')
  .map(t => t.id);

/** Lookup tool config by id */
export function getToolConfig(id) {
  return TOOLS.find(t => t.id === id) ?? null;
}
`;

mkdirSync(OUT_DIR, { recursive: true });
writeFileSync(OUT_PATH, code, 'utf-8');

console.log(`✔ Generated ${OUT_PATH} (${schema.tools.length} tools, schema v${schema.version})`);

// ── Sync SUPPORTED_TOOLS to install/uninstall scripts ───────────────────
const shellList = ids.map(id => `"${id}"`).join(' ');
const psList = ids.map(id => `"${id}"`).join(', ');

const SHELL_TOOL_TARGETS = [
  { path: 'scripts/common.sh',    pattern: /^SUPPORTED_TOOLS=\([^)]*\)/m,  replacement: `SUPPORTED_TOOLS=(${shellList})` },
  { path: 'scripts/common.ps1',   pattern: /^\$SupportedTools = @\([^)]*\)/m, replacement: `$SupportedTools = @(${psList})` },
];

let toolSyncCount = 0;
for (const target of SHELL_TOOL_TARGETS) {
  const fullPath = join(ROOT, target.path);
  const content = readFileSync(fullPath, 'utf-8');
  if (!target.pattern.test(content)) {
    console.error(`  ✘ ${target.path} — SUPPORTED_TOOLS pattern not found`);
    continue;
  }
  const updated = content.replace(target.pattern, target.replacement);
  if (content !== updated) {
    writeFileSync(fullPath, updated, 'utf-8');
    console.log(`  ✔ ${target.path} → ${ids.length} tools synced`);
    toolSyncCount++;
  } else {
    console.log(`  · ${target.path} — already up to date`);
  }
}

if (toolSyncCount > 0) {
  console.log(`\n  Tool IDs synced to ${toolSyncCount} script(s).`);
}
