import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest';
import { mkdirSync, rmSync, existsSync, writeFileSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { CopilotAdapter } from '../../src/adapters/copilot.js';

const TEST_DIR = join(import.meta.dirname, '__test_copilot__');

beforeEach(() => {
  mkdirSync(TEST_DIR, { recursive: true });
});

afterEach(() => {
  vi.restoreAllMocks();
  rmSync(TEST_DIR, { recursive: true, force: true });
});

describe('CopilotAdapter', () => {
  const adapter = new CopilotAdapter();

  it('has toolName "copilot"', () => {
    expect(adapter.toolName).toBe('copilot');
  });

  it('getUserDir returns ~/.copilot', () => {
    expect(adapter.getUserDir()).toContain('.copilot');
  });

  it('getSkillsDir returns ~/.copilot/skills', () => {
    expect(adapter.getSkillsDir()).toContain(join('.copilot', 'skills'));
  });

  it('getCommandsDir returns ~/.copilot/instructions', () => {
    expect(adapter.getCommandsDir()).toContain(join('.copilot', 'instructions'));
  });

  it('supportsPlugin returns false', () => {
    expect(adapter.supportsPlugin()).toBe(false);
  });

  it('install copies skills and creates copilot-instructions.md', () => {
    vi.spyOn(adapter, 'getUserDir').mockReturnValue(join(TEST_DIR, '.copilot'));

    const loomRoot = join(TEST_DIR, 'loom-root');
    mkdirSync(join(loomRoot, 'skills', 'test-skill'), { recursive: true });
    writeFileSync(join(loomRoot, 'skills', 'test-skill', 'SKILL.md'), '# Test');

    const log = adapter.install(loomRoot, '1.0.0');
    expect(existsSync(join(TEST_DIR, '.copilot', 'skills', 'test-skill', 'SKILL.md'))).toBe(true);

    const instructionsPath = join(TEST_DIR, '.copilot', 'copilot-instructions.md');
    expect(existsSync(instructionsPath)).toBe(true);
    const content = readFileSync(instructionsPath, 'utf-8');
    expect(content).toContain('Generated by loom');
    expect(content).toContain('1.0.0');
    expect(content).toContain('test-skill');
  });

  it('install copies templates to loom-init-project skill dir', () => {
    vi.spyOn(adapter, 'getUserDir').mockReturnValue(join(TEST_DIR, '.copilot'));

    const loomRoot = join(TEST_DIR, 'loom-root');
    mkdirSync(join(loomRoot, 'skills', 'loom-init-project'), { recursive: true });
    writeFileSync(join(loomRoot, 'skills', 'loom-init-project', 'SKILL.md'), '# Init');
    mkdirSync(join(loomRoot, 'templates'), { recursive: true });
    writeFileSync(join(loomRoot, 'templates', 'constitution.md'), '# Template');

    adapter.install(loomRoot, '1.0.0');

    const templatesDir = join(TEST_DIR, '.copilot', 'skills', 'loom-init-project', 'templates');
    expect(existsSync(join(templatesDir, 'constitution.md'))).toBe(true);
  });

  it('install skips templates when loom-init-project not found', () => {
    vi.spyOn(adapter, 'getUserDir').mockReturnValue(join(TEST_DIR, '.copilot'));

    const loomRoot = join(TEST_DIR, 'loom-root');
    mkdirSync(join(loomRoot, 'skills', 'other-skill'), { recursive: true });
    writeFileSync(join(loomRoot, 'skills', 'other-skill', 'SKILL.md'), '# Other');
    mkdirSync(join(loomRoot, 'templates'), { recursive: true });
    writeFileSync(join(loomRoot, 'templates', 'constitution.md'), '# Template');

    const log = adapter.install(loomRoot, '1.0.0');

    expect(log.some(l => l.includes('not found, skipped'))).toBe(true);
  });

  it('install skips existing copilot-instructions.md', () => {
    vi.spyOn(adapter, 'getUserDir').mockReturnValue(join(TEST_DIR, '.copilot'));
    mkdirSync(join(TEST_DIR, '.copilot'), { recursive: true });
    writeFileSync(join(TEST_DIR, '.copilot', 'copilot-instructions.md'), '# Existing');

    const loomRoot = join(TEST_DIR, 'loom-root');
    mkdirSync(join(loomRoot, 'skills'), { recursive: true });

    const log = adapter.install(loomRoot, '1.0.0');
    expect(log.some(l => l.includes('already exists'))).toBe(true);
    expect(readFileSync(join(TEST_DIR, '.copilot', 'copilot-instructions.md'), 'utf-8')).toBe('# Existing');
  });

  it('uninstall removes skills, templates, and loom instructions', () => {
    vi.spyOn(adapter, 'getUserDir').mockReturnValue(join(TEST_DIR, '.copilot'));
    mkdirSync(join(TEST_DIR, '.copilot', 'skills', 'loom-test'), { recursive: true });
    writeFileSync(join(TEST_DIR, '.copilot', 'skills', 'loom-test', 'SKILL.md'), '# Test');
    mkdirSync(join(TEST_DIR, '.copilot', 'skills', 'loom-init-project', 'templates'), { recursive: true });
    writeFileSync(join(TEST_DIR, '.copilot', 'skills', 'loom-init-project', 'templates', 'test'), 'test');
    mkdirSync(join(TEST_DIR, '.copilot'), { recursive: true });
    writeFileSync(join(TEST_DIR, '.copilot', 'copilot-instructions.md'), '<!-- Generated by loom -->\n# Loom');

    adapter.uninstall(TEST_DIR);

    expect(existsSync(join(TEST_DIR, '.copilot', 'copilot-instructions.md'))).toBe(false);
    expect(existsSync(join(TEST_DIR, '.copilot', 'skills', 'loom-test'))).toBe(false);
    expect(existsSync(join(TEST_DIR, '.copilot', 'skills', 'loom-init-project', 'templates'))).toBe(false);
  });

  it('uninstall skips non-loom copilot-instructions.md', () => {
    vi.spyOn(adapter, 'getUserDir').mockReturnValue(join(TEST_DIR, '.copilot'));
    mkdirSync(join(TEST_DIR, '.copilot'), { recursive: true });
    writeFileSync(join(TEST_DIR, '.copilot', 'copilot-instructions.md'), '# My Custom Instructions');

    adapter.uninstall(TEST_DIR);
    expect(existsSync(join(TEST_DIR, '.copilot', 'copilot-instructions.md'))).toBe(true);
  });
});
